### ISSUE TITLE
3rd Edition typo on p. 169

### ISSUE THREAD

**Issue by christianvye** [wesm/pydata-book#164]
Since MSFT is a valid Python variable name, we can also select these columns using
more concise syntax:
In [285]: returns["MSFT"].corr(returns["IBM"])

should be as in 2nd Edition:
returns.MSFT.corr(returns.IBM)

Otherwise there is no difference between the [283] code and the [285] code. Thanks.

**Comment by wesm** [comment]
I had intended to remove the uses of attributes from the 3rd edition — I will fix the text preceding the code example. Thank you!

**Comment by christianvye** [comment]
You are welcome. I’m enjoying the book and am using it as part of a course
on Data Analytics and Visualization for an accelerated Masters program in
Data Science at URI.
Thanks for writing pandas!

**Comment by christianvye** [comment]
Found another one in the 3rd edition:
In [110]: ax.title("Changes in log(m1) versus log(unemp)")
should be plt.title
on p. 312.
Correct in the 2nd edition.

**Comment by wesm** [comment]
These issues are both fixed in the notebooks and will be corrected on https://wesmckinney.com/book

**Comment by pouria-81** [comment]
Hi,
I working on your Book "Python for Data Analysis" second edition when trying Chapter 7. Data Aggregation and Group Operations cell 53 "def peak_to_peak(arr):
    return arr.max() - arr.min()" 
grouped.agg(peak_to_peak)

I receive an error "TypeError: unsupported operand type(s) for -: 'str' and 'str'" and I have tried everything and even looked for the third edition of your book. 
why is this error and what is the solution???

**Comment by christianvye** [comment]
I didn't have any problem with that bit of code from Chapter 10, Version2.:

Data Aggregation
<https://jupyter.uri.edu/user/christianvye/lab/tree/ProblemSolutions/ch10.ipynb#Data-Aggregation>
[5]:

df

grouped = df.groupby('key1')

grouped['data1'].quantile(0.9)

[5]:

key1
a    1.668413
b   -0.523068
Name: data1, dtype: float64

[6]:

def peak_to_peak(arr):

    return arr.max() - arr.min()

grouped.agg(peak_to_peak)

[6]:
data1data2
key1
a 2.170488 1.300498
b 0.036292 0.487276

**Comment by pouria-81** [comment]
this is really weird, since I followed each step like its mentioned in the book and even the Jupyter Notebook,  in the beginning its my IDE causing the error. 
I started to code on colab and later I switched to Jupyter and I have still the same error: "TypeError: unsupported operand type(s) for -: 'str' and 'str'". 

anyway thanks for the quick response, I will check everything.

**Comment by christianvye** [comment]
Do you have “ around the function? Or is that just how you described it?
